### ISSUE TITLE
`enable and disable` implementation doesn't corresponds to the documentation

### ISSUE THREAD

**Issue by niklasad1** [lu-zero/autotools-rs#13]
Hey,

According to the docs for [enable and disable](https://github.com/lu-zero/autotools-rs/blob/master/src/lib.rs#L158-#L166l) `opt parameter` is supposed to not require to begin with a `-` but the implementation never concatenate with a `-` https://github.com/lu-zero/autotools-rs/blob/master/src/lib.rs#L348-#L361 

So for example: 
`.enable("foo", None) -> --enablefoo`

**Comment by lu-zero** [comment]
You are right, we should concatenate with `-`

**Comment by niklasad1** [comment]
Thanks :+1:
