### ISSUE TITLE
provide a method to run the configure script separately from building via `make`

### ISSUE THREAD

**Issue by radhermit** [lu-zero/autotools-rs#31]
This functionality would be useful when some rust code only requires headers to be available that are generated via running the configure script, e.g. config.h, and doesn't need to build the target via `make`.

From glancing through the code it doesn't look like the functionality is split in this fashion yet so one can only run the configure script while also running a pointless build via `make`.

**Comment by lu-zero** [comment]
Sounds reasonable, if you have a patch ready I'd merge it, otherwise poke me in the weekend and I'll add it.

**Comment by radhermit** [comment]
> Sounds reasonable, if you have a patch ready I'd merge it, otherwise poke me in the weekend and I'll add it.

Sorry, I haven't had time for writing a patch, but I don't think it should be hard if you want to do it yourself.

**Comment by lu-zero** [comment]
Please test it when you have time :)

**Comment by radhermit** [comment]
> Please test it when you have time :)

Works great, thanks a lot.

Unfortunately, it also helped me realize building bash headers currently still requires running `make` to build a single header file with a single dynamically-defined value injected via the configure script into the makefile which then injects it into the header. :laughing:

That can possibly be fixed by patching the build system, but I have doubts upstream will accept it. Anyway, thanks again for the work on this.

If you're interested what projects I'm using it for it's with [scallop](https://github.com/pkgcraft/scallop) that wraps bash and the [pkgcraft-bash](https://github.com/pkgcraft/pkgcraft-bash) that builds plugins able to be dynamically loaded by bash.
