### ISSUE TITLE
`cflags` doesn't work

### ISSUE THREAD

**Issue by ndarilek** [lu-zero/autotools-rs#8]
Thanks for this! Looks like it has the potential to help solve some annoying problems with cross-platform builds for one of my crates.

I notice that the `.cflags(...)` method doesn't seem to do anything, other than push to a variable that is never referenced again.

I'm working on a fairly complex build that needs lots of native libs. Essentially what I need to do is set `-I out_dir/include` so dependent libraries' headers can be found. Wondering if that might be a sensible default, or if a helper might be added to set that up?

Thanks again.

**Comment by lu-zero** [comment]
It could be a sensible default indeed, and probably adding to the `pkg-config` path the install dir by default.
